/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vehiclesofinterestdesktop;


import java.awt.Color;
import static java.awt.Color.HSBtoRGB;
import java.awt.Component;
import java.awt.Font;
import java.awt.List;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.border.Border;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableModel;

/**
 *
 * @author Shristi Amatya
 */
public class MainScreen extends javax.swing.JFrame {

    /**
     * Creates new form ROI
     */
    public MainScreen() {
        initComponents();
        jTable1.getTableHeader().setOpaque(false);
        jTable1.getTableHeader().setBackground(Color.red);
     
        resetActionButtonsSelected(addForms);
      
        loadVoi();
       
        setColumnsTOCenter();
        
        isMAKESelected = false;
        isROISelected = false;
        isMODELSelected = false;
        isVOISelected = true;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnVOI = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnMake = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnROI = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        btnModel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        addForms = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(238, 238, 240));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        btnVOI.setBackground(new java.awt.Color(255, 255, 255));
        btnVOI.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 51), 2));
        btnVOI.setToolTipText("voi");
        btnVOI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnVOIMousePressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Vehicle of Interest (VOI)");
        jLabel1.setAlignmentX(0.5F);

        javax.swing.GroupLayout btnVOILayout = new javax.swing.GroupLayout(btnVOI);
        btnVOI.setLayout(btnVOILayout);
        btnVOILayout.setHorizontalGroup(
            btnVOILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnVOILayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnVOILayout.setVerticalGroup(
            btnVOILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnVOILayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnMake.setBackground(new java.awt.Color(255, 255, 255));
        btnMake.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 51), 2));
        btnMake.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnMakeMousePressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Make");
        jLabel3.setAlignmentX(0.5F);
        jLabel3.setMaximumSize(new java.awt.Dimension(30, 15));
        jLabel3.setMinimumSize(new java.awt.Dimension(30, 15));

        javax.swing.GroupLayout btnMakeLayout = new javax.swing.GroupLayout(btnMake);
        btnMake.setLayout(btnMakeLayout);
        btnMakeLayout.setHorizontalGroup(
            btnMakeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnMakeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnMakeLayout.setVerticalGroup(
            btnMakeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnMakeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnROI.setBackground(new java.awt.Color(255, 255, 255));
        btnROI.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 51), 2));
        btnROI.setToolTipText("roi");
        btnROI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnROIMousePressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Reason of Interest");

        javax.swing.GroupLayout btnROILayout = new javax.swing.GroupLayout(btnROI);
        btnROI.setLayout(btnROILayout);
        btnROILayout.setHorizontalGroup(
            btnROILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnROILayout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnROILayout.setVerticalGroup(
            btnROILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnROILayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnModel.setBackground(new java.awt.Color(255, 255, 255));
        btnModel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 51), 2));
        btnModel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnModelMousePressed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Model");
        jLabel6.setAlignmentX(0.5F);

        javax.swing.GroupLayout btnModelLayout = new javax.swing.GroupLayout(btnModel);
        btnModel.setLayout(btnModelLayout);
        btnModelLayout.setHorizontalGroup(
            btnModelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnModelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnModelLayout.setVerticalGroup(
            btnModelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnModelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(255, 204, 51));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 94, Short.MAX_VALUE)
        );

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Shristi Amatya\\Documents\\NetBeansProjects\\VehiclesOfInterestDesktop\\lo.PNG")); // NOI18N
        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 32, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnROI, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnVOI, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnMake, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(btnModel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 137, Short.MAX_VALUE)
                .addComponent(btnVOI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnMake, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79)
                .addComponent(btnROI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(189, 189, 189))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(417, Short.MAX_VALUE)
                    .addComponent(btnModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(255, 255, 255)))
        );

        jPanel1.setBackground(new java.awt.Color(238, 238, 240));

        jTable1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTable1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "LICENSE_PLATE", "REASON", "MAKE", "MODEL", "VEH_YEAR", "COLOR", "OWNERS_NAME", "OWNERS_PHONE"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jTable1.setAutoscrolls(false);
        jTable1.setRowHeight(50);
        jTable1.setSelectionBackground(new java.awt.Color(253, 233, 115));
        jTable1.setShowHorizontalLines(true);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.getTableHeader().setBackground(Color.red);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        jTable1.getAccessibleContext().setAccessibleParent(jPanel1);

        jPanel4.setBackground(new java.awt.Color(255, 204, 51));

        jLabel7.setBackground(new java.awt.Color(255, 204, 51));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Hi Patricia!");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        addForms.setBackground(new java.awt.Color(255, 204, 51));
        addForms.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        addForms.setText("Add");
        addForms.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        addForms.setOpaque(true);
        addForms.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addFormsMouseClicked(evt);
            }
        });
        addForms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFormsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 901, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addForms, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78)
                .addComponent(addForms, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

     DefaultTableModel model ;
     VehiclesOfInterestController voi = new VehiclesOfInterestController();
     boolean isVOISelected = false;
     boolean isROISelected = false;
     boolean isMAKESelected = false;
     boolean isMODELSelected = false;
        
    private void btnModelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModelMousePressed
        // TODO add your handling code here:
        //to control which add form to show
        isMODELSelected = true;
        isVOISelected = false;
        isROISelected = false;
        isMAKESelected = false;
        
        setColor(btnModel);
        resetColor(btnVOI);
        resetColor(btnMake);
        resetColor(btnROI); 
      loadModel();
      setColumnsTOCenter();

    }//GEN-LAST:event_btnModelMousePressed

    private void btnROIMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnROIMousePressed
        // TODO add your handling code here:
        //to control which add form to show
        isROISelected = true;
        isMODELSelected = false;
        isVOISelected = false;
        isMAKESelected = false;
        
        setColor(btnROI);
        resetColor(btnMake);
        resetColor(btnVOI);
        resetColor(btnModel);
    loadROI();
    setColumnsTOCenter();
         
    }//GEN-LAST:event_btnROIMousePressed

    private void btnMakeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMakeMousePressed
        // TODO add your handling code here:
        //to control which add form to show
        isMAKESelected = true;
        isROISelected = false;
        isMODELSelected = false;
        isVOISelected = false;
      
        setColor(btnMake);
        resetColor(btnVOI);
        resetColor(btnROI);
        resetColor(btnModel);
       loadMake();
       setColumnsTOCenter();
             
    }//GEN-LAST:event_btnMakeMousePressed

    private void addFormsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFormsActionPerformed
        // TODO add your handling code here:
       setActionButtonsSelected(addForms);
        
     ROI addroi = new ROI();
     MAKE addmake = new MAKE();
     MODEL addmodel = new MODEL();
     VOI addvoi = new VOI();
     //System.out.print(isROISelected );
   if(isROISelected){
       addroi.setVisible(true);      
   }
   else if(isMAKESelected){
 
   addmake.setVisible(true);
   } 
   else if(isMODELSelected){
 
   addmodel.setVisible(true);
   } 
    else if(isVOISelected){
 
   addvoi.setVisible(true);
   } 
   
   else{
      addroi.setVisible(false);
      addmake.setVisible(false);
       addmodel.setVisible(false);
       addvoi.setVisible(false);
  }
     
      //btn_make
    }//GEN-LAST:event_addFormsActionPerformed
 
 
    
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

          int index = jTable1.getSelectedRow();
         TableModel model = jTable1.getModel();
         
       if(isROISelected){
         ROI editROI = new ROI();
         editROI.addReason.setEditable(false);
         
         editROI.jButton1.setVisible(false);
         editROI.btn_update.setVisible(true);
         editROI.btn_delete.setVisible(true);
          resetActionButtonsSelected( editROI.btn_update);
          resetActionButtonsSelected( editROI.btn_delete);
         editROI.jLabel1.setText("Reason of Interest");
            String reason = model.getValueAt(index, 0).toString();
            
            String description = model.getValueAt(index, 1).toString();

            editROI.setVisible(true);
            editROI.pack();
            editROI.addReason.setText(reason);
            editROI.addDescription.setText(description);
         }
         if(isMAKESelected){
             MAKE make = new MAKE();
              make.addMake.setEditable(false);
              
             make.jButton1.setVisible(false);
             make.btn_delete.setVisible(true);
             resetActionButtonsSelected(make.btn_delete);
             make.jLabel1.setText(" Make - Vehicle of Interest.");
             
             String makeField = model.getValueAt(index, 0).toString();
              make.setVisible(true);
              make.pack();
              make.addMake.setText(makeField);
         }
         if(isMODELSelected){
          MODEL vehModel = new MODEL();
           vehModel.addmodel.setEditable(false);
           vehModel.addmake.setEditable(false);
               
             vehModel.jButton1.setVisible(false);
             vehModel.btn_delete.setVisible(true);
             resetActionButtonsSelected(vehModel.btn_delete);
             vehModel.jLabel1.setText("Model - Vehicle of Interest.");
             
              String modelField = model.getValueAt(index, 0).toString();
             String vehMakeField = model.getValueAt(index, 1).toString();
            
             
              vehModel.setVisible(true);
              vehModel.pack();
              vehModel.addmake.setSelectedItem(vehMakeField);
              vehModel.addmodel.setText(modelField);   
         }
          if(isVOISelected){
                 VOI editVOI = new VOI();
                 editVOI.addlicensPlate.setEditable(false);
                 
              editVOI.jButton1.setVisible(false);
              editVOI.btn_update.setVisible(true);
              editVOI.btn_delete.setVisible(true);
                resetActionButtonsSelected( editVOI.btn_update);
                resetActionButtonsSelected( editVOI.btn_delete);
              editVOI.jLabel1.setText("Vehicle of Interest");
              
            String licensePlate = model.getValueAt(index, 0).toString();
            String voi_reason = model.getValueAt(index, 1).toString();
            String veh_make = model.getValueAt(index, 2).toString();
            String veh_model = model.getValueAt(index, 3).toString();
            String year = model.getValueAt(index, 4).toString();
            String color = model.getValueAt(index, 5).toString();  
            String owname = model.getValueAt(index, 6).toString();
            String owphone = model.getValueAt(index, 7).toString();
            
            
            editVOI.setVisible(true);
            editVOI.pack();

            editVOI.addlicensPlate.setText(licensePlate);
            editVOI.roidropdown.setSelectedItem(voi_reason);
            editVOI.makedropdown.setSelectedItem(veh_make);
            editVOI.modeldropdown.setSelectedItem(veh_model);
            editVOI.addyear.setText(year);
            editVOI.addcolor.setText(color);            
            editVOI.addowname.setText(owname);
            editVOI.addowphone.setText(owphone);
            
         }
         
    }//GEN-LAST:event_jTable1MouseClicked

    private void addFormsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addFormsMouseClicked
        // TODO add your handling code here: 
        
    }//GEN-LAST:event_addFormsMouseClicked

    private void btnVOIMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVOIMousePressed
        // TODO add your handling code here:
        
        isMAKESelected = false;
        isROISelected = false;
        isMODELSelected = false;
        isVOISelected = true;
        
        setColor(btnVOI);
        resetColor(btnMake);
        resetColor(btnROI);
        resetColor(btnModel);
       loadVoi();
       //setColumnsTOCenter();
       
    }//GEN-LAST:event_btnVOIMousePressed
void setColor(JPanel panel){
    panel.setBackground(new java.awt.Color(255,204,51));
}
void resetColor(JPanel panel){
    panel.setBackground(new java.awt.Color(255,255,255));
}
void btn_SetColor(JPanel panel, JLabel label){
    panel.setBackground(new java.awt.Color(153,0,0));
    label.setForeground(new java.awt.Color(255,204,51));
}
void btn_ResetColor(JPanel panel,JLabel label){
    panel.setBackground(new java.awt.Color(255,204,51));
    label.setForeground(new java.awt.Color(0,0,0));
}
void loadTBLData( DefaultTableModel model,String[][] data){
    for(String[] rowData : data){
    model.addRow(rowData);
    }    
}
void setActionButtonsSelected(JButton button){
button.setOpaque(true);
button.setBackground(new java.awt.Color(153,0,0));  //maroon
button.setForeground(new java.awt.Color(255,204,51));
button.setBorderPainted(false);
}

void resetActionButtonsSelected(JButton button){
button.setOpaque(true);
button.setBackground(new java.awt.Color(255,204,51));  //yellow
button.setForeground(new java.awt.Color(0,0,0));
button.setBorderPainted(false);
}

void loadVoi(){
    resetActionButtonsSelected(addForms);
  model = (DefaultTableModel) jTable1.getModel();
        model.setColumnCount(0);
        model.setRowCount(0);
        model.addColumn("LICENSE PLATE");
        model.addColumn("REASON");
        model.addColumn("MAKE");
        model.addColumn("MODEL");
        model.addColumn("VEHICLE YEAR");
        model.addColumn("COLOR");
        model.addColumn("OWNERS_NAME");
        model.addColumn("OWNERS_PHONE");
        model = (DefaultTableModel) jTable1.getModel();
        String[][] data = voi.allVehicleOfInterest();
        loadTBLData(model,data);
    
}

void loadMake(){
    resetActionButtonsSelected(addForms);
  model = (DefaultTableModel) jTable1.getModel();
        model.setColumnCount(0);
        model.setRowCount(0);
        model.addColumn("MAKE");
        String[] stringArray  = voi.allVehicleMake();
         String[][] string2DArray = new String[stringArray.length][stringArray.length];

       // System.out.print( model.getColumnName(stringArray.length));
        // Copy elements from stringArray to string2DArray
        for (int i = 0; i < stringArray.length; i++) {
            string2DArray[i][0] = stringArray[i];
        }
        // Print the resulting 2D array
        for (String[] row : string2DArray) {
           model.addRow(row);
         }
}
void loadROI(){
    resetActionButtonsSelected(addForms);
    model = (DefaultTableModel) jTable1.getModel();
        model.setColumnCount(0);
        model.setRowCount(0);
        model.addColumn("REASON");
        model.addColumn("DESCRIPTION");
        String[][] data = voi.getAllReasonsForInterest();
        loadTBLData(model,data);
}
void loadModel(){
    resetActionButtonsSelected(addForms);
  model = (DefaultTableModel) jTable1.getModel();
        model.setColumnCount(0);
           model.setRowCount(0);
        model.addColumn("MODEL");
         model.addColumn("MAKE");
        String[][] data = voi.allVehicleModel();
          loadTBLData(model,data);
}

public void setColumnsTOCenter(){
DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
centerRenderer.setHorizontalAlignment(SwingConstants.CENTER);

 JTableHeader tableHeader = jTable1.getTableHeader();
 tableHeader.setBackground(Color.red);
 
 tableHeader.setDefaultRenderer(centerRenderer);
 // tableHeader.setOpaque(true);
 //tableHeader.setBackground(new java.awt.Color(153,0,0));
 //tableHeader.setForeground(new java.awt.Color(255,204,51));
 //Border headerBorder = tableHeader.getBorder();
 //tableHeader.setBorder(new Border(headerBorder.));
 
 
 Font headerFont = tableHeader.getFont();
 tableHeader.setFont(new Font(headerFont.getName(),Font.BOLD,20));

for (int i = 0; i < jTable1.getColumnCount(); i++) {
                jTable1.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
            }
}


 public void close(){
    WindowEvent closeWindow = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
    Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closeWindow);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainScreen().setVisible(true);
                
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addForms;
    private javax.swing.JPanel btnMake;
    private javax.swing.JPanel btnModel;
    private javax.swing.JPanel btnROI;
    private javax.swing.JPanel btnVOI;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
