/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vehiclesofinterestdesktop;

import java.sql.SQLException;
import javax.swing.JButton;

/**
 *
 * @author Shristi Amatya
 */
public class VOI extends javax.swing.JFrame {

    /**
     * Creates new form AddVOI
     */
    public VOI() {
        initComponents();
        fillcombo();
        btn_update.setVisible(false);
        btn_delete.setVisible(false);
         resetActionButtonsSelected(jButton1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        model = new javax.swing.JLabel();
        addyear = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        licensPlate = new javax.swing.JLabel();
        addcolor = new javax.swing.JTextField();
        make = new javax.swing.JLabel();
        addlicensPlate = new javax.swing.JTextField();
        color = new javax.swing.JLabel();
        year = new javax.swing.JLabel();
        owphone = new javax.swing.JLabel();
        addowphone = new javax.swing.JTextField();
        owname = new javax.swing.JLabel();
        addowname = new javax.swing.JTextField();
        roi = new javax.swing.JLabel();
        roidropdown = new javax.swing.JComboBox<>();
        makedropdown = new javax.swing.JComboBox<>();
        modeldropdown = new javax.swing.JComboBox<>();
        btn_update = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 204, 51));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Add Vehicle of Interest");
        jLabel1.setOpaque(true);

        model.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        model.setText("Vehicle Model :");

        addyear.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jButton1.setBackground(new java.awt.Color(255, 204, 51));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Save");
        jButton1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton1MousePressed(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        licensPlate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        licensPlate.setText("License Plate :");

        addcolor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        make.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        make.setText("Vehicle Make :");

        addlicensPlate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        color.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        color.setText("Vehicle Color :");

        year.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        year.setText("Vehicle Year :");

        owphone.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        owphone.setText("Owner's Phone :");

        addowphone.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        addowphone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addowphoneActionPerformed(evt);
            }
        });

        owname.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        owname.setText("Owner's Name :");

        addowname.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        addowname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addownameActionPerformed(evt);
            }
        });

        roi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        roi.setText("Reason of Interest : ");

        roidropdown.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        roidropdown.setAutoscrolls(true);
        roidropdown.setRequestFocusEnabled(false);
        roidropdown.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                roidropdownMousePressed(evt);
            }
        });

        makedropdown.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        makedropdown.setAutoscrolls(true);
        makedropdown.setOpaque(true);
        makedropdown.setRequestFocusEnabled(false);
        makedropdown.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                makedropdownMousePressed(evt);
            }
        });

        modeldropdown.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        modeldropdown.setAutoscrolls(true);
        modeldropdown.setRequestFocusEnabled(false);
        modeldropdown.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                modeldropdownMousePressed(evt);
            }
        });

        btn_update.setBackground(new java.awt.Color(255, 204, 51));
        btn_update.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_update.setText("Update");
        btn_update.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btn_update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_updateMousePressed(evt);
            }
        });
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });

        btn_delete.setBackground(new java.awt.Color(255, 204, 51));
        btn_delete.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_delete.setText("Delete");
        btn_delete.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btn_delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_deleteMousePressed(evt);
            }
        });
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(licensPlate, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(make, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(roi, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(owname, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(year, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(model, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(owphone, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(color, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(93, 93, 93)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(makedropdown, javax.swing.GroupLayout.Alignment.LEADING, 0, 341, Short.MAX_VALUE)
                                            .addComponent(addowphone, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(addyear, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(modeldropdown, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addComponent(roidropdown, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(addcolor, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(addowname, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(addlicensPlate, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_update, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 693, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(licensPlate, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(roi, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(addlicensPlate, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(roidropdown, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(make, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(makedropdown, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modeldropdown, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(model, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addyear, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(year, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(color, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(owname, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(owphone, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(addcolor, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(addowname, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(addowphone, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_update, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 VehiclesOfInterestController voi = new VehiclesOfInterestController();
  Confirmation confirm = new Confirmation();
  
    private void jButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MousePressed
        // TODO add your handling code here:
         //confirm.setValue("Successfully added new rows!");
         //confirm.setVisible(true);
    }//GEN-LAST:event_jButton1MousePressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      setActionButtonsSelected(jButton1);
              
        voi.createVehicleOfInterest(
                addlicensPlate.getText()
                , roidropdown.getSelectedItem().toString()
                , makedropdown.getSelectedItem().toString()
                , modeldropdown.getSelectedItem().toString()
                , addyear.getText()
                , addcolor.getText()
                , addowname.getText()
                , addowphone.getText()
        );   
        addlicensPlate.setEditable(false);roidropdown.setEditable(false);makedropdown.setEditable(false);modeldropdown.setEditable(false);addyear.setEditable(false);
        addcolor.setEditable(false);addowname.setEditable(false);addowphone.setEditable(false);
        
        if (voi.errorMessage.equals(" ")){
        confirm.setValue("Add Successful!");
        }else{
             confirm.jTextField1.setBackground(new java.awt.Color(153,0,0));
             confirm.jTextField1.setForeground(new java.awt.Color(255,204,51));
            confirm.setValue("Add Failed: Duplicate.");
            
        }
         confirm.setVisible(true);
         confirm.jTextField1.setEditable(false);     
    }//GEN-LAST:event_jButton1ActionPerformed

    private void addownameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addownameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addownameActionPerformed

    private void makedropdownMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_makedropdownMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_makedropdownMousePressed

    private void roidropdownMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roidropdownMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_roidropdownMousePressed

    private void modeldropdownMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modeldropdownMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_modeldropdownMousePressed

    private void btn_updateMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_updateMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_updateMousePressed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
      
        setActionButtonsSelected(btn_update);
         
         voi.updateVehicleOfInterest(
                 addlicensPlate.getText()
                , roidropdown.getSelectedItem().toString()
                ,  makedropdown.getSelectedItem().toString() 
                ,  modeldropdown.getSelectedItem().toString()
                , addyear.getText() 
                , addcolor.getText() 
                , addowname.getText() 
                 ,addowphone.getText()
         );
          addlicensPlate.setEditable(false);roidropdown.setEditable(false);makedropdown.setEditable(false);modeldropdown.setEditable(false);addyear.setEditable(false);
        addcolor.setEditable(false);addowname.setEditable(false);addowphone.setEditable(false);
        
        if (voi.errorMessage.equals(" ")){
        confirm.setValue("Update Successful!");
        }else{
             confirm.jTextField1.setBackground(new java.awt.Color(153,0,0));
             confirm.jTextField1.setForeground(new java.awt.Color(255,204,51));
            confirm.setValue("Update Failed: Try Again!");
            
        }
         confirm.setVisible(true);
         confirm.jTextField1.setEditable(false);  
         
    }//GEN-LAST:event_btn_updateActionPerformed

    private void btn_deleteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_deleteMousePressed
         setActionButtonsSelected(btn_delete);  
         voi.deleteVehicleOfInterest(addlicensPlate.getText());
        addlicensPlate.setEditable(false);roidropdown.setEditable(false);makedropdown.setEditable(false);modeldropdown.setEditable(false);addyear.setEditable(false);
        addcolor.setEditable(false);addowname.setEditable(false);addowphone.setEditable(false);
        
        if (voi.errorMessage.equals(" ")){
        confirm.setValue("Delete Successful!");
        }else{
             confirm.jTextField1.setBackground(new java.awt.Color(153,0,0));
             confirm.jTextField1.setForeground(new java.awt.Color(255,204,51));
            confirm.setValue("Cannot delete existing value.");
            
        }
         confirm.setVisible(true);
         confirm.jTextField1.setEditable(false);  
    }//GEN-LAST:event_btn_deleteMousePressed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void addowphoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addowphoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addowphoneActionPerformed

    void fillcombo(){
    //voi.allVehicleMakeKey();
     for(String makeKey : voi.allVehicleMakeKey()){
    makedropdown.addItem(makeKey);
    }
    for(String modelkey : voi.allVehicleModelKey()){
    modeldropdown.addItem(modelkey);
    }
    for(String rois : voi.allReasonsForInterestKey()){
    roidropdown.addItem(rois);
    }
    //voi.allReasonsForInterestKey();
    }
    
    void setActionButtonsSelected(JButton button){
button.setOpaque(true);
button.setBackground(new java.awt.Color(153,0,0));  //maroon
button.setForeground(new java.awt.Color(255,204,51));
button.setBorderPainted(false);
}

void resetActionButtonsSelected(JButton button){
button.setOpaque(true);
button.setBackground(new java.awt.Color(255,204,51));  //yellow
button.setForeground(new java.awt.Color(0,0,0));
button.setBorderPainted(false);
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VOI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VOI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VOI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VOI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VOI().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField addcolor;
    public javax.swing.JTextField addlicensPlate;
    public javax.swing.JTextField addowname;
    public javax.swing.JTextField addowphone;
    public javax.swing.JTextField addyear;
    public javax.swing.JButton btn_delete;
    public javax.swing.JButton btn_update;
    private javax.swing.JLabel color;
    public javax.swing.JButton jButton1;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JPanel jPanel1;
    private javax.swing.JLabel licensPlate;
    private javax.swing.JLabel make;
    public javax.swing.JComboBox<String> makedropdown;
    private javax.swing.JLabel model;
    public javax.swing.JComboBox<String> modeldropdown;
    private javax.swing.JLabel owname;
    private javax.swing.JLabel owphone;
    private javax.swing.JLabel roi;
    public javax.swing.JComboBox<String> roidropdown;
    private javax.swing.JLabel year;
    // End of variables declaration//GEN-END:variables
}
